version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: production
  ignore:
    # Newer client versions incompatible - see https://opensearch.org/docs/clients/index/
    - dependency-name: elasticsearch

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
