language: python
python:
  - "3.6"
env:
  - ES_VERSION=5.4.2 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch > /dev/null &
  - make requirements-dev
script:
  - PYTEST_ARGS='--cov=app --cov-report=term-missing' make test
notifications:
  email: false
