language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - ES_VERSION=6.7.0
before_install:
  - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch > /dev/null &
install:
  - make requirements-dev
script:
  - PYTEST_ARGS='--cov=app --cov-report=term-missing' make test
notifications:
  email: false
